### ISSUE TITLE
Command.class is missing from jar

### ISSUE THREAD

**Issue by fygrave** [splunk/splunk-sdk-java#70]
Some of older packages expect that Command.class is under com.splunk, which is absent in jar (moved to util/com/splunk/). Breaks some older code.

**Comment by shakeelmohamed** [comment]
Hi @fygrave,

Can you give us a bit more information, like which packages?

Thanks!

**Comment by fygrave** [comment]
here are a few: 

 https://github.com/elfsternberg/splunk-search-clojure
in core.clj:

(ns splunksearch.core
  (:require [clojure.java.io :refer :all])
  (:import (com.splunk Service ServiceArgs Args ResultsReaderJson ResultsReaderCsv ResultsReaderXml Event))
  (:import (com.splunk Command))
  (:import (java.io InputStreamReader OutputStreamWriter)))

in splunk sdk examples:

https://github.com/splunk/splunk-sdk-java/blob/master/examples/com/splunk/examples/search_oneshot/Program.java
https://github.com/splunk/splunk-sdk-java/blob/master/examples/com/splunk/examples/index/Program.java

etc.

**Comment by shakeelmohamed** [comment]
Thanks for that info!

The `Command` class has been in the `util/com/splunk` directory since v1.0 ([relevant commit](https://github.com/splunk/splunk-sdk-java/commit/bea5c83978880d23c2a13bddd195043d22da09c4)), this is not something we plan to change. In this case, the package does not match the file structure but our build script takes care of that.

If you look at the [Usage section in the splunk-search-clojure README](https://github.com/elfsternberg/splunk-search-clojure#usage), you'll see some general directions for manually copying over the Command class.

As for the Java SDK examples, you shouldn't have any problems if you follow the directions on [dev.splunk.com](http://dev.splunk.com/view/java-sdk/SP-CAAAEFE) or in the [README](https://github.com/splunk/splunk-sdk-java#run-examples).

**Comment by shakeelmohamed** [comment]
Hi @fygrave,

We've decided to make [this change](https://github.com/splunk/splunk-sdk-java/commit/4a88c3aa0923c5300709eabd6a9f1822d52c45f5) on the develop branch

**Comment by fygrave** [comment]
Thanks. This would make building 3rd party packages so much easier!

**Comment by fygrave** [comment]
I guess the issue can be closed now :)
